### ISSUE TITLE
need a simple way to update pbbam... or don't bundle it

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbbamr#6]
I think the copy of pbbam in here is problematic for some reasons.  I was OK with it before, but today I realized that unless it is kept up to date, we won't be able to keep up to date with the chemistries recognized by  pbbam, and this could (I think) result in not even being able to load new BAM files.

**Comment by evolvedmicrobe** [comment]
The pbbam library is very simple to update, it's a few shell commands, see the README on the front of the GitHub.  The real problem is with issues like:

https://github.com/PacificBiosciences/pbbamr/issues/1

Where functionality lands in pbbamr before it lands in pbbam, this could continue to need to happen in the future as any bug or missing functionality in pbbamr is blocking, so needs to be fixed ASAP, which might be faster than the code review schedule for pbbam fixes.  Hopefully there won't be many more if any of these though.

There is really no way around not bundling pbbam though, it has a CMAKE dependency and does not include a makefile by default, which is a non-starter for R (yes, there are hideously complex work arounds, but they are far worse than a few cp commands in my book).  

pbbamr is already a botched package because it can't work on windows. I think this needs move in the direction of becoming more, not less, cran compatible.

**Comment by dalexander** [comment]
OK

**Comment by evolvedmicrobe** [comment]
I suppose we could have a git hook setup so that pushes to pbbam on github update pbbamr automatically and run tests here.  That seems like a good idea, though I am already over committed for the near future though, perhaps @natechols or @pb-cdunn have some git ninja skills to set that up quickly?

**Comment by dalexander** [comment]
No it's fine for nwo
